/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package java.util;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Date extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Date\",\"namespace\":\"java.util\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new Date RecordBuilder */
  public static java.util.Date.Builder newBuilder() {
    return new java.util.Date.Builder();
  }
  
  /** Creates a new Date RecordBuilder by copying an existing Builder */
  public static java.util.Date.Builder newBuilder(java.util.Date.Builder other) {
    return new java.util.Date.Builder(other);
  }
  
  /** Creates a new Date RecordBuilder by copying an existing Date instance */
  public static java.util.Date.Builder newBuilder(java.util.Date other) {
    return new java.util.Date.Builder(other);
  }
  
  /**
   * RecordBuilder for Date instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Date>
    implements org.apache.avro.data.RecordBuilder<Date> {


    /** Creates a new Builder */
    private Builder() {
      super(java.util.Date.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(java.util.Date.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Date instance */
    private Builder(java.util.Date other) {
            super(java.util.Date.SCHEMA$);
    }

    @Override
    public Date build() {
      try {
        Date record = new Date();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
